services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    environment:
      Db__ConnString: "Host=db;Port=5432;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=${POSTGRES_DB}"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/App:z
      - /App/src/Domain/obj
      - /App/src/Domain/bin
      - /App/src/Application/obj
      - /App/src/Application/bin
      - /App/src/Infrastructure/obj
      - /App/src/Infrastructure/bin
      - /App/src/Presentation/obj
      - /App/src/Presentation/bin
    depends_on: 
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/App:z
      - /App/node_modules
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # necessary for scaffolding
    ports:
      - "5432:5432"
    volumes:
      - projectmanagementapp_pgdata:/var/lib/postgresql/
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
          test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
          interval: 5s
          timeout: 5s
          retries: 5
    
volumes:
  projectmanagementapp_pgdata:
